name: color-estimator
channels:
- defaults
dependencies:
- h5py>=2.7,<3
- hdf5>=1.8,<2
- mkl=2017.0.3
- pip=9.0.1
- python=3.6.2
- pyyaml
- scipy=0.19.1
- pip:
  - colorama
  - Keras==2.2.0
  - Pillow==5.1.0
  - tensorflow-gpu==1.8.0
  - tqdm
